docs/_build/html/_modules/pointtree/instance_segmentation/_multi_stage_algorithm.html
src/pointtree/instance_segmentation/_multi_stage_algorithm.py

This pull request fixes the following bug: The canopy height model may be computed using the tree crown points only. In that case, some tree trunk points can be located outside the boundaries of the canopy height model. Therefore, a check is added to ensure that the canopy height model is only accessed with valid indices.

Keep grid indices within boundaries of CHM

---

.github/workflows/clean-up-pull-requests.yml
coverage.svg

This pull request fixes the Github workflow that removes the documentation deployment of a pull request after the pull request is merged or closed.

docs: fix workflow for removing docs deployment after a PR is closed

---

README.md

This pull request updates the outdated links to the package documentation in the Readme.

docs: update links to documentation in Readme

---

.coveragerc

Remove .coveragerc file as the `coverage` package was replaced by the `pytets-cov` package in #39.

ci: remove unused .coveragerc

---

.coveragerc

This pull request re-adds the .coveragerc file that was removed in #45 since this file is still needed by pytest-cov.

ci: re-add .coveragerc

---

.github/workflows/clean-up-pull-requests.yml

Sets the concurrency for the PR clean-up workflow. Unfortunately, Github does not provide an option to disable skipping runs queued between the run in-progress and the latest queued (see [#41518](https://github.com/orgs/community/discussions/41518)). If several pull requests are merged shortly after each other, this can result in no clean-up being carried out for some of them.

ci: set concurrency for PR clean-up workflow

---

pyproject.toml

This pull request removes the parameterized package from the package dependencies since it is not used anymore.

ci: remove parameterized from dependencies

---

.github/workflows/clean-up-pull-requests.yml

This pull request fixes the rclone setup in the PR clean-up CI workflow, which was broken by #62.

ci: fix PR clean-up workflow

---

.github/workflows/release-package.yml

This pull request adapts the release Github workflow to allow it to push the release commit to the main branch, bypassing the branch protection rules as suggested [here](https://github.com/sbellone/release-workflow-example).

ci: fix release workflow

---

Dockerfile

This pull request adds an SSH client to the pointtree Docker image since this is needed for the release workflow implemented in #65.

ci: install SSH client in Docker image

---

docs/source/conf.py

Extend list of nitpick ignores for sphinx to silence warnings in docs build.

docs: extend nitpick ignores

---

docs/source/develop/index.rst

This pull request adds a section to the documentation that documents how to setup the pre-commit hooks of the repository.

docs: document setup of pre-commit hooks

---

docs/source/conf.py

This pull request fixes a bug in the generation of the documentation page that allows selecting the package version for which to show the package documentation. The bug resulted in the wrong package version being tagged as `(stable)`.

docs: fix version sorting

---

pyproject.toml
src/pointtree/instance_segmentation/_multi_stage_algorithm.py
src/pointtree/instance_segmentation/filters.py
test/instance_segmentation/test_filters.py
test/instance_segmentation/test_multi_stage_algorithm.py

This pull request adds the module `pointtree.instance_segmentation.filters` that provides the following methods to filter instances:
- `filter_instances_min_points`: Removes instances with too few points.
- `filter_instances_vertical_extent`: Removes instances whose extent in z-direction is too small.
BREAKING CHANGE: the `filter_trunk_clusters` method is removed from the `MultiStageAlgorithm` class and replaced by the new filter methods.

feat: add operations to filter instances

---

test/instance_segmentation/test_multi_stage_algorithm.py

This pull request fixes the test for the `MultiStageAlgorithm.watershed_correction` method, which failed due to changes in the latest version of the scikit-image package.

ci: fix test for MultiStageAlgorithm.watershed_correction

---

src/pointtree/operations/_create_digital_terrain_model.py

Suppresses the division by zero warning in `pointtorch.operations.create_digital_terrain_model`.

refactor: suppress division by zero warning in create_digital_terrain_model

---

src/pointtree/operations/__init__.py
src/pointtree/operations/_polygon_area.py
test/operations/test_polygon_area.py

This pull request adds a method `pointtree.operations.polygon_area` that computes the area of a polygon from its vertices.

feat: operation to compute polygon area

---

mypy_stubs/sklearn/linear_model.pyi
src/pointtree/operations/__init__.py
src/pointtree/operations/_estimate_with_linear_model.py
test/operations/test_estimate_with_linear_model.py

This pull request adds a method `pointtorch.operations.estimate_with_linear_model` that fits a linear model to a training dataset and computes the model's predictions for a given dataset.

feat: estimate with linear model

---

pyproject.toml

remove torch, torch-cluster, torch-scatter from pyproject.toml since these dependencies must be installed manually

refactor: remove torch dependencies from pyproject.toml

---

src/pointtree/operations/_create_digital_terrain_model.py

Refactors `pointtree.operations.create_digital_terrain_model` to support numpy arrays of different types and adds a `num_workers` parameter.

refactor: create digital terrain model

---

src/pointtree/operations/_distance_to_dtm.py

Refactors `pointtree.operations.distance_to_dtm` to support numpy arrays of different types and fixes a bug in the clipping of coordinates.

refactor: distance_to_dtm

---

src/pointtree/evaluation/_instance_segmentation_metrics.py
src/pointtree/evaluation/_match_instances.py
test/evaluation/test_instance_segmentation_metrics.py
test/evaluation/test_match_instances.py

The pull request fixes the instance segmentation metrics to correctly handle cases where all predictions are false positives or false negatives.

fix: instance segmentation metrics when all predictions are false positives or false negatives

---

src/pointtree/evaluation/_instance_segmentation_metrics.py
test/evaluation/test_instance_segmentation_metrics.py

Refactors the computation of instance segmentation metrics for the case where no valid detections exist

refactor: computation of instance segmentation metrics
